FROM ubuntu:18.04

LABEL maintainer="REDACTED"

RUN apt-get update -y && \
    apt-get install -y python3-pip python-dev

# We copy just the requirements.txt first to leverage Docker cache
COPY ./ci/requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip3 install -r requirements.txt

COPY . /app

RUN cd /app && python create_tables.py

ENTRYPOINT [ "python3" ]

CMD [ "car_api.py" ]
